---
abstract: 'Catmandu modules for working with BibTeX data'
author:
  - 'Nicolas Steenlant C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-BibTeX
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  BibTeX::Parser: 0
  Catmandu: 0
  LaTeX::Encode: 0
  Moo: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-BibTeX/issues
  homepage: https://github.com/LibreCat/Catmandu-BibTeX
  repository: https://github.com/LibreCat/Catmandu-BibTeX.git
version: 0.05
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
